# Simulating Coin Flips

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# outcome of one coin flip
np.random.randint(0,2)

0

In [7]:
# outcomes of ten thousand coin flips
np.random.randint(0,2,size=10000)

array([0, 1, 1, ..., 1, 0, 1])

In [8]:
np.random.randint(0,2,size=10000).mean()

0.5012

In [9]:
x=np.random.randint(0,2,size=10000)
x

array([1, 0, 0, ..., 0, 1, 0])

In [14]:
x.mean()

0.491

In [15]:
np.bincount(x)

array([5090, 4910], dtype=int64)

In [16]:
zeros=np.bincount(x)[0]
zeros

5090

In [17]:
ones=np.bincount(x)[1]
ones

4910

In [19]:
# mean outcome of ten thousand coin flips
np.random.randint(2,size=10000).mean()

0.5031

In [25]:
# outcome of one coin flip
np.random.choice([0,1])

1

In [26]:
# outcome of ten thousand coin flips
np.random.choice([0,1],size=10000)

array([0, 1, 1, ..., 1, 0, 0])

In [27]:
# mean outcome of ten thousand coin flips
np.random.choice([0,1],size=10000).mean()

0.4976

In [31]:
# outcomes of ten thousand biased coin flips
np.random.choice([0,1],size=10000,p=[0.8,0.2])

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0,1],size=10000,p=[0.8,0.2]).mean()

0.203